services:
  - type: web
    name: smartstudy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn smartstudy.wsgi:application
    envVars:
      - key: GROQ_API_KEY
        sync: false